# Generated by Django 4.2.3 on 2023-08-09 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(db_column='Categoria', max_length=16)),
            ],
            options={
                'db_table': 'categoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(db_column='Marca', max_length=16)),
            ],
            options={
                'db_table': 'marca',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(db_column='Modelo', max_length=16)),
                ('marca', models.ForeignKey(db_column='Marca_id', on_delete=django.db.models.deletion.DO_NOTHING, to='distr.marca')),
            ],
            options={
                'db_table': 'modelo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('saida', models.IntegerField(db_column='Saida')),
                ('obs', models.CharField(db_column='Obs', max_length=40)),
                ('wins', models.DateTimeField()),
            ],
            options={
                'db_table': 'movimento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(db_column='Tipo', max_length=16)),
            ],
            options={
                'db_table': 'tipo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('subcategoria', models.CharField(db_column='Subcategoria', max_length=16)),
                ('categoria', models.ForeignKey(db_column='Categoria_id', on_delete=django.db.models.deletion.DO_NOTHING, to='distr.categoria')),
            ],
            options={
                'db_table': 'subcategoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ean', models.CharField(db_column='EAN', max_length=13)),
                ('quantidade', models.IntegerField(db_column='Quantidade')),
                ('custo', models.DecimalField(db_column='Custo', decimal_places=2, max_digits=12)),
                ('preco', models.DecimalField(db_column='Preco', decimal_places=2, max_digits=12)),
                ('categoria', models.ForeignKey(db_column='Categoria_id', on_delete=django.db.models.deletion.DO_NOTHING, to='distr.categoria')),
                ('marca', models.ForeignKey(db_column='Marca_id', on_delete=django.db.models.deletion.DO_NOTHING, to='distr.marca')),
                ('modelo', models.ForeignKey(db_column='Modelo_id', on_delete=django.db.models.deletion.DO_NOTHING, to='distr.modelo')),
                ('subcategoria', models.ForeignKey(db_column='Subcategoria_id', on_delete=django.db.models.deletion.DO_NOTHING, to='distr.subcategoria')),
                ('tipo', models.ForeignKey(db_column='Tipo_id', on_delete=django.db.models.deletion.DO_NOTHING, to='distr.tipo')),
            ],
            options={
                'db_table': 'produto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField(db_column='Quantidade')),
                ('custo', models.DecimalField(db_column='Custo', decimal_places=2, max_digits=12)),
                ('preco', models.DecimalField(db_column='Preco', decimal_places=2, max_digits=12)),
                ('movimento', models.ForeignKey(db_column='Movimento_id', on_delete=django.db.models.deletion.DO_NOTHING, to='distr.movimento')),
                ('produto', models.ForeignKey(db_column='Produto_id', on_delete=django.db.models.deletion.DO_NOTHING, to='distr.produto')),
            ],
            options={
                'db_table': 'item',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantidade', models.IntegerField(db_column='Quantidade')),
                ('produto', models.ForeignKey(db_column='Produto_id', on_delete=django.db.models.deletion.DO_NOTHING, to='distr.produto')),
            ],
            options={
                'db_table': 'etiqueta',
                'managed': True,
            },
        ),
    ]
